NAME = iter

cc = c++

CFLAGS = -Wall -Wextra -Werror -std=c++98

SRC = main.cpp

all : $(NAME)

$(NAME) : $(SRC)
	$(cc) $(CFLAGS) $(SRC) -o $(NAME)

clean :

fclean :
	rm -rf $(NAME)

re : fclean all
